apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 533267327181.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:fc48cfde900d9fde26707d30d35594fbd65c51e3
        ports:
        - containerPort: 80
