apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 339713069769.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:f2cca66c9491c1beb854a3a23f47794b780bd209
        ports:
        - containerPort: 80
