apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 339713069769.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:4e9e73ebc6011797ab5543207419a0b93ef94964
        ports:
        - containerPort: 80
