apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 339713069769.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:1c7d5b673c376801611c4c0053bb77a240b45c33
        ports:
        - containerPort: 80
