apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 339713069769.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:20ed126f2480a50f163433e35bc43135d27d69f2
          ports:
            - containerPort: 5000
