apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 533267327181.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:47ebe401c2403520a1dd77f97dddf7817fefb00b
          ports:
            - containerPort: 5000
