apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 339713069769.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:20ed126f2480a50f163433e35bc43135d27d69f2
        ports:
        - containerPort: 80
