apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 533267327181.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:0449861d34dc6a58f24902905adf6c8b42a8e8fb
        ports:
        - containerPort: 80
