apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 533267327181.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:47ebe401c2403520a1dd77f97dddf7817fefb00b
        ports:
        - containerPort: 80
