apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 533267327181.dkr.ecr.us-east-1.amazonaws.com/shopping-site-main:47ebe401c2403520a1dd77f97dddf7817fefb00b
        ports:
        - containerPort: 80

