apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 822849401317.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:488b30623c5af8087a1bf479676cfb887936fffa
        ports:
        - containerPort: 80
