apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 822849401317.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:488b30623c5af8087a1bf479676cfb887936fffa
        ports:
        - containerPort: 80
