apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 905418310012.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:d531b2d76a8e4a9190f66a2b5db58a108a8f0c83
        ports:
        - containerPort: 80
