apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 339713069769.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:1c7d5b673c376801611c4c0053bb77a240b45c33
        ports:
        - containerPort: 80
