apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 533267327181.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:fc48cfde900d9fde26707d30d35594fbd65c51e3
        ports:
        - containerPort: 80
